getAll getById for admin and user
ohalushchak-exadel/internship-team2-java pull request #20
Opened 2021-07-05 20:47 UTC by OlegKandalov

-added service RoleCheckService
- added logic where user cannot take deleted elements

2021-07-05 21:13 UTC, ohalushchak-exadel requested changes

2021-07-05 21:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/CategoryController.java
> +        if (isDeleted & roleCheckService.isUser()) {
`&&`

2021-07-05 21:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/CategoryController.java
> +        if (categoryDto.isDeleted() & roleCheckService.isUser()) {
`&&`

2021-07-05 21:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/SubCategoryController.java
> +        if (isDeleted & roleCheckService.isUser()) {
`&&`

2021-07-05 21:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/SubCategoryController.java
> +        if (subCategoryDto.isDeleted() & roleCheckService.isUser()) {
`&&`

2021-07-05 21:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/VendorController.java
> +        if (isDeleted & roleCheckService.isUser()) {
`&&`

2021-07-05 21:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/VendorController.java
> +        if (vendorResponseDto.isDeleted() & roleCheckService.isUser()) {
`&&`

2021-07-05 21:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/VendorLocationController.java
> +        if (isDeleted & roleCheckService.isUser()) {
`&&`

2021-07-05 21:13 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/VendorLocationController.java
> +        if (locationResponseDto.isDeleted() & roleCheckService.isUser()) {
`&&`

2021-07-06 09:12 UTC, ohalushchak-exadel approved these changes

2021-07-06 12:29 UTC, nkharitoniuk approved these changes

2021-07-06 22:21 UTC, merged