Discounts and email sender
ohalushchak-exadel/internship-team2-java pull request #24
Opened 2021-07-12 11:40 UTC by nazarevitsch

2021-07-12 11:46 UTC, ohalushchak-exadel commented on pom.xml
> +			<version>2.2.5.RELEASE</version>
do you need this specific version? Why not use the one that comes from spring-boot-starter-parent?

2021-07-12 12:51 UTC, ohalushchak-exadel requested changes

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/exception/UnacceptableDiscountDtoException.java
> +public class UnacceptableDiscountDtoException extends RuntimeException {
Give it a more generic name to use it for all "bad request" cases and use it instead of DiscrepancyException as well

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/model/dto/DiscountDto.java
> +    }
this is what mappers are for

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/model/dto/DiscountUpdateDto.java
> +    }
move to  mapper (just use the map() method there)

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/model/dto/DiscountDto.java
> +    private UUID categoryId;
`@NotNull`

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/model/dto/DiscountDto.java
> +    private UUID vendorId;
`@NotNull`

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/model/dto/DiscountDto.java
>      private ZonedDateTime endDate;
Validate that start date is less or equal to end date. End date should be at least 'today'

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/model/dto/DiscountDtoResponse.java
> +public class DiscountDtoResponse {
extend DiscountDto

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/repository/DiscountRepositoryCustom.java
> +        if (city != null && country != null) {
let them filter just by country as well

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/domain/Discount.java
> +    private UUID vendorId;
`@NotNull`

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/domain/Discount.java
> +    private UUID categoryId;
`@NotNull`

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/domain/Discount.java
> +    private int percent;
`@Min` + `@Max`

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/model/dto/DiscountUpdateDto.java
> +public class DiscountUpdateDto {
make some base DTO which will share fields used in create/update/response dtos

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/model/dto/DiscountUpdateDto.java
> +    private UUID categoryId;
`@NotNull`

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +    private DiscountMapper discountMapper;
make them `private final` and use `@RequiredArgsConstructor` for the class

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +    public void updateDiscount(UUID id, DiscountUpdateDto discountUpdateDto) {
return updated discount

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +        throw new NotFoundException("Discount with such id doesn't exist.");
always executed. missed `return` inside `if`

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +            if (locationsIds == null || locationsIds.isEmpty()){
CollectionUtils.IsEmpty()

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +            for (int i = 0; i < vendorLocations.size(); i++) {
`for (VendorLocation vl : vendorLocations)`

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +                throw new UnacceptableDiscountDtoException("Discount hasn't full data!");
message is too generic

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +                if (!vendorLocations.get(i).getVendor().getId().equals(discount.getVendorId())) throw new DiscrepancyException("Vendor location doesn't belong to vendor.");
throw `NotFound` here. Clients don't need to know that such location exists at all.

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +                if (vendorLocations.get(i).isDeleted()) throw new DeletedException("Vendor location is deleted.");
which location?

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +            throw new UnacceptableDiscountDtoException("Discount hasn't full data!");
message is too generic

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +        }
same as location

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/DiscountController.java
> +        return new ResponseEntity<>(new Message("Discount was updated!"), HttpStatus.OK);
return updated discount

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/DiscountController.java
> +        return new ResponseEntity<>(new Message("Discount was deleted."), HttpStatus.OK);
just HttpStatus.OK. No message needed

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/UserController.java
> +    private EmailNotificationService emailNotificationService;
unused

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/resources/liquibase/01.07.2021_nazarii_alter_discount_and_category_relationship.xml
> +</databaseChangeLog>
since you're creating the `discount` table in the same PR, just add this columns to the `create` changeset

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/domain/Discount.java
> +    private int percent;
percentage
and use it everywhere

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/resources/liquibase/29.06.2021_nazarii_create_discount_and_its_relationship.xml
> +            <column name="dsc_sub_category_id" type="UUID"/>
nullable="false"

2021-07-12 12:51 UTC, ohalushchak-exadel commented on src/main/resources/liquibase/29.06.2021_nazarii_create_discount_and_its_relationship.xml
> +            <column name="dvl_vendor_location_id" type="UUID"/>
nullable="false"

2021-07-13 08:48 UTC, nazarevitsch commented on src/main/java/com/exadel/discount/platform/repository/DiscountRepositoryCustom.java
> +        if (city != null && country != null) {
But idea was, that customer can filter discount by city and country at the same time.

2021-07-13 09:19 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +        return discountMapper.entityToDto(discount.orElseThrow(()-> new NotFoundException("Discount wasn't found.")));
add id to the message

2021-07-13 09:19 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +                .orElseThrow(() -> new NotFoundException("Discount doesn't exist."));
add id to the message

2021-07-13 09:19 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +        throw new NotFoundException("Discount with such id doesn't exist.");
which id?

2021-07-13 09:20 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +            throw new BadRequestException("Duration of discount is unacceptable.");
why unacceptable?

2021-07-13 09:20 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +                throw new BadRequestException("Duration of discount is unacceptable.");
why unacceptable?

2021-07-13 09:21 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +                throw new BadRequestException("Discount hasn't full data!");
which data is missing?

2021-07-13 09:26 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +            throw new BadRequestException("Discount hasn't full data!");
what data is missing?

2021-07-13 09:26 UTC, ohalushchak-exadel commented on src/main/resources/liquibase/master.xml
> +    <include file="25.06.2021_nazarii_insert_user_locations.xml" relativeToChangelogFile="true"/>
where's this file?
you're only adding 29.06.2021_nazarii_create_discount_and_its_relationship.xml in this PR

2021-07-13 09:26 UTC, ohalushchak-exadel commented on src/main/resources/liquibase/master.xml
> +    <include file="23.06.2021_nazarii_alter_user_location_table.xml" relativeToChangelogFile="true"/>
where's this file?
you're only adding 29.06.2021_nazarii_create_discount_and_its_relationship.xml in this PR

2021-07-13 09:58 UTC, nazarevitsch commented on src/main/resources/liquibase/master.xml
> +    <include file="25.06.2021_nazarii_insert_user_locations.xml" relativeToChangelogFile="true"/>
![изображение](https://user-images.githubusercontent.com/45229160/125432530-1e02d295-c8ec-40f4-91cf-4b319c3fe7b6.png)

2021-07-13 10:07 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/DiscountService.java
> +                throw new BadRequestException("If location/s of discount isn't online, it should has locations.");
should *have*

2021-07-13 10:14 UTC, ohalushchak-exadel approved these changes

2021-07-13 10:47 UTC, merged