Tag service controller repository liquibase
ohalushchak-exadel/internship-team2-java pull request #7
Opened 2021-06-22 12:11 UTC by AndriiBondarenko2

2021-06-22 12:35 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/TagController.java
> +        if (tagDto == null) {
what is this check for? service throws an exception if there's no tag with the give id

2021-06-22 12:35 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/TagController.java
> +        }
this should be and already is in a service

2021-06-22 12:35 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/TagController.java
> +        return new ResponseEntity<>(tagDto, HttpStatus.OK);
return the updated tag, not the one you've received as a param

2021-06-22 12:35 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/TagController.java
> +    public void sendToArchive(@PathVariable UUID id) throws Exception {
return ResponseEntity<Void> for consistency

2021-06-22 12:35 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/TagCrudServiceImpl.java
> +        Tag tag1 = tagRepository.save(tag);
don't use numbers to differentiate variables. Give them meaningful names like `savedTag`

2021-06-22 12:35 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/TagCrudServiceImpl.java
> +        tagRepository.save(tag);
so where's the update?
use mapper.map(tagDto, tag) to actually update the tag

2021-06-22 12:35 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/TagCrudServiceImpl.java
> +            throw new Exception("is not exist by id");
wait for the https://github.com/ohalushchak-exadel/internship-team2-java/pull/5 to be merged and use NotFoundException here and in the .orElseThrow() calls of this service

2021-06-22 12:44 UTC, AndriiBondarenko2 commented on src/main/java/com/exadel/discount/platform/service/TagCrudServiceImpl.java
> +        tagRepository.save(tag);
I will fix it

2021-06-23 08:36 UTC, ohalushchak-exadel requested changes

2021-06-23 08:36 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/TagCrudServiceImpl.java
> +        Tag tag;
should be `=` instead of `;`

2021-06-23 08:36 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/TagCrudServiceImpl.java
> +        tag = mapper.dtoToEntity(tagDto);
you should map `tagDto` onto already existing `tag`. Make sure not to update the id.

2021-06-23 08:36 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/TagController.java
> +    }
use `@RequiredArgsConstructor` instead

2021-06-23 17:44 UTC, ohalushchak-exadel approved these changes

2021-06-24 07:07 UTC, nkharitoniuk approved these changes

2021-06-24 07:50 UTC, merged