vendor and vendorLocation
ohalushchak-exadel/internship-team2-java pull request #8
Opened 2021-06-23 09:30 UTC by OlegKandalov

vendorLocation:
- mapper
- repo
- service
- controller
vendor:
- controller

2021-06-23 09:41 UTC, ohalushchak-exadel requested changes

2021-06-23 09:41 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/converter/VendorLocationMapper.java
> +    ModelMapper modelMapper;
private

2021-06-23 09:41 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/VendorController.java
> +    @PostMapping(value = "/add",
remove `value = "/add",`. Post method is used for creation so it's obvious that you're creating a new vendor

2021-06-23 09:41 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/VendorController.java
> +    @PutMapping(value = "/update",
should be`value = "/{id}"`. Put method is used for update so it's obvious that you're updating a vendor and you need to specify the id of the resource  which you're updating.

2021-06-23 09:41 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/web/VendorLocationController.java
> +
same as for vendorController

2021-06-23 09:41 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/VendorLocationServiceImpl.java
> +        location = mapper.dtoToEntity(vendorLocationDto);
map `vendorLocationDto` onto already existing location and make sure not to update the id

2021-06-23 09:41 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/VendorLocationServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Vendor with id " + id +
Vendor was not found?

2021-06-23 09:41 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/VendorLocationServiceImpl.java
> +            throw new NotFoundException("Location with id " + id +
we have 2 different Location entities in the project so be more specific  here

2021-06-23 13:10 UTC, ohalushchak-exadel commented on src/main/java/com/exadel/discount/platform/service/VendorLocationServiceImpl.java
> +    public VendorLocationResponseDto update(UUID id, VendorLocationDto vendorLocationDto) {
use this DTO in Get/GetAll as well

2021-06-23 15:41 UTC, OlegKandalov commented on src/main/java/com/exadel/discount/platform/converter/VendorLocationMapper.java
> +    public <S, T> List<T> mapList(List<S> source, Class<T> targetClass) {
i took this method from the site: https://www.baeldung.com/java-modelmapper-lists 
))

2021-06-23 17:45 UTC, ohalushchak-exadel approved these changes

2021-06-24 07:09 UTC, nkharitoniuk commented on src/main/java/com/exadel/discount/platform/converter/VendorLocationMapper.java
> +    public <S, T> List<T> mapList(List<S> source, Class<T> targetClass) {
It's just a suggestion to use a library for example https://stackabuse.com/guide-to-mapstruct-in-java-advanced-mapping-library

2021-06-24 07:10 UTC, nkharitoniuk approved these changes

2021-06-24 07:33 UTC, merged